// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5hfkkOCdrnPaYchX45G-jKKr1KQ4V_k8',
    appId: '1:1000848559378:web:76b7fac31d93a9cda677cb',
    messagingSenderId: '1000848559378',
    projectId: 'furniture-1a645',
    authDomain: 'furniture-1a645.firebaseapp.com',
    storageBucket: 'furniture-1a645.appspot.com',
    measurementId: 'G-D70ZDGVE6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtNLLNp3TGe6JPEjPoKTBSc49bGvsmX4s',
    appId: '1:1000848559378:android:defd9f06048a20bba677cb',
    messagingSenderId: '1000848559378',
    projectId: 'furniture-1a645',
    storageBucket: 'furniture-1a645.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOgFXstVI9U67xfGTHdNO6WndPtOT-iew',
    appId: '1:1000848559378:ios:8a6e5bd6d33bbda2a677cb',
    messagingSenderId: '1000848559378',
    projectId: 'furniture-1a645',
    storageBucket: 'furniture-1a645.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOgFXstVI9U67xfGTHdNO6WndPtOT-iew',
    appId: '1:1000848559378:ios:caabfaea4479ecfba677cb',
    messagingSenderId: '1000848559378',
    projectId: 'furniture-1a645',
    storageBucket: 'furniture-1a645.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
